
version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      args:
        - NODE_ENV=${NODE_ENV:-production}
    container_name: language_app_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5000
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASS:-postgres}@db:5432/${DB_NAME:-language_app}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-your_sendgrid_api_key}
      - EMAIL_FROM=${EMAIL_FROM:-your_email@example.com}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-your_stripe_secret_key}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-your_stripe_webhook_secret}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/.env:/app/.env:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - language_app_network
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - VITE_API_URL=${VITE_API_URL:-/api}
    container_name: language_app_frontend
    restart: always
    ports:
      - "8080:80"  # Mapeo para Lovable environment
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - language_app_network
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:14-alpine
    container_name: language_app_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-language_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - language_app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-language_app}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  language_app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    # Aseguramos que los datos persistan en un volumen externo
    name: language_app_postgres_data
